version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "8090:8088"
    networks:
      - "default"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
